// Datos que no cambian con el idioma
export const PROFILE = {
    name: "Juan David Ducuara",
    email: "jducuara82@gmail.com",
    linkedin: "https://www.linkedin.com/in/juandaducuara",
    github: "https://github.com/juandaducuara",
    cv: "./cv-juan-ducuara.pdf",
    photo: "./assets/images/juan-ducuara.jpg",
}

export const HERO_TECH_ICONS = [
    { name: "C#", icon: "./assets/images/tech/csharp.svg" },
    { name: ".NET", icon: "./assets/images/tech/dotnetcore.svg" },
    { name: "Angular", icon: "./assets/images/tech/angular.svg" },
    { name: "TypeScript", icon: "./assets/images/tech/typescript.svg" },
]

const NAV_IDS = {
    inicio: "#seccionInicio",
    experiencia: "#seccionExperienciaLaboral",
    proyectos: "#seccionProyectos",
    habilidades: "#seccionHabilidades",
    estudios: "#seccionEstudiosRealizados",
    contacto: "#seccionContacto",
}

// Contenido por idioma. Ambas claves deben tener la misma estructura.
export const CONTENT = {
    es: {
        nav: [
            { href: NAV_IDS.inicio, label: "Inicio" },
            { href: NAV_IDS.experiencia, label: "Experiencia" },
            { href: NAV_IDS.proyectos, label: "Proyectos" },
            { href: NAV_IDS.habilidades, label: "Habilidades" },
            { href: NAV_IDS.estudios, label: "Estudios" },
        ],
        ui: {
            contactBtn: "Contáctame",
            langToggle: "EN",
            langToggleLabel: "View in English",
            menuLabel: "Abrir menú",
            downloadCv: "Descargar CV",
            current: "Actual",
            highlights: "Logros clave",
            showAllTasks: "Ver todas las funciones",
            featured: "Destacado",
        },
        hero: {
            role: "Desarrollador Full Stack",
            summary: "Tecnólogo en Análisis y Desarrollo de Sistemas con enfoque en backend y arquitectura de aplicaciones. Hoy construyo plataformas de gestión de riesgo y cumplimiento con Angular 21 y ASP.NET Core 9: integración de sistemas, seguridad, procesamiento de datos y automatización de procesos.",
            facts: [
                { icon: "location_on", text: "Bogotá, Colombia" },
                { icon: "work_history", text: "Desarrollando software desde 2023" },
                { icon: "translate", text: "Inglés B1" },
            ],
            photoAlt: "Foto de Juan David Ducuara",
        },
        experience: {
            title: "Experiencia laboral",
            items: [
                {
                    role: "Ingeniero de Desarrollo",
                    company: "Risk Consulting",
                    location: "Bogotá, Colombia",
                    date: "Mar 2026 - Actualidad",
                    current: true,
                    highlights: [
                        "Construí frontend y backend de una plataforma nueva con Angular 21 y ASP.NET Core 9 que reemplaza un sistema legado en PHP",
                        "Diseñé formularios dinámicos guiados por metadata: un formulario nuevo se crea solo con datos, sin tocar código",
                        "Cerré una vulnerabilidad IDOR implementando control de acceso por rol y por recurso",
                        "Configuré CI/CD en Azure DevOps con versionado CalVer y promoción entre Pruebas, Preproducción y Producción",
                    ],
                    responsabilities: [
                        "Desarrollo de plataformas web de gestión de riesgo y cumplimiento (KYC / SAGRILAFT / PTEE) para los sectores farmacéutico, energético, de consumo masivo e industrial",
                        "Flujos de aprobación multi-rol (Contraparte, BPO, Compliance, Legal, Business Owner, Administrador) con máquina de estados, devoluciones, escalamiento, tareas y notificaciones",
                        "Integración con Adobe Sign (varios firmantes y webhooks), Microsoft Entra ID / SSO, Inspektor (listas restrictivas), Cloudflare Turnstile y SMTP con plantillas editables",
                        "Módulos de scoring y perfilamiento de riesgo y matrices de controles con cálculo de riesgo residual",
                        "Reportería e indicadores: bitácoras, dashboards por rol y exportes a Excel y PDF con paginación del lado del servidor",
                        "Migración de datos del sistema PHP/V1 al V2: mapeo de estados y catálogos, deduplicación de personas, firmas históricas y cargues masivos desde Excel",
                        "Seguridad con JWT y refresh token, rate limiting, cifrado con BCrypt y auditoría de acciones",
                        "Más de 75 migraciones de base de datos versionadas, transacciones atómicas, SOLID, Clean Architecture y conventional commits",
                        "Soporte evolutivo y correctivo a aplicaciones heredadas en ASP.NET MVC 5 / EF6, Laravel y PHP nativo, con despliegue en IIS",
                        "Interfaces responsive y bilingües (ES/EN) con modo oscuro, accesibilidad y tutoriales guiados",
                    ],
                    stack: ["Angular 21", "ASP.NET Core 9", "SQL Server", "Azure DevOps", "Entra ID", "Adobe Sign"],
                },
                {
                    role: "Desarrollador Full Stack",
                    company: "NyGSoft SAS",
                    location: "Bogotá, Colombia",
                    date: "Abr 2024 - Feb 2026",
                    highlights: [
                        "Desarrollé aplicaciones empresariales en C# / .NET con SOLID y Clean Architecture",
                        "Implementé microservicios y APIs RESTful con middleware, versionamiento y seguridad con JWT",
                        "Construí interfaces SPA con React (PrimeReact) y Vue (PrimeVue) integradas con APIs REST",
                    ],
                    responsabilities: [
                        "Integración de APIs externas y servicios internos con patrones Repository y Unit of Work",
                        "Bases de datos SQL Server, Oracle y MySQL: consultas optimizadas, procedimientos almacenados y Entity Framework Core",
                        "Mantenimiento de sistemas en PHP (Laravel, CodeIgniter 4) y desarrollo de APIs RESTful en Laravel con arquitectura MVC",
                        "Interfaces con jQuery para módulos internos",
                        "Análisis funcional, diseño técnico, documentación y estimación de tareas en equipos multidisciplinarios",
                    ],
                    stack: [".NET", "C#", "React", "Vue", "Laravel", "SQL Server", "Oracle"],
                },
                {
                    role: "Practicante de Desarrollo de Sistemas de Información",
                    company: "AOA Colombia",
                    location: "Bogotá, Colombia",
                    date: "Ago 2023 - Feb 2024",
                    highlights: [
                        "Desarrollé y mantuve módulos web con PHP, JavaScript y MySQL",
                        "Creé y consumí APIs REST para integrar sistemas",
                    ],
                    responsabilities: [
                        "Diseño y estructuración de bases de datos relacionales",
                        "Implementación de lógica de negocio y validaciones en el backend",
                        "Pruebas funcionales y corrección de errores",
                    ],
                    stack: ["PHP", "JavaScript", "MySQL"],
                },
            ],
        },
        projects: {
            title: "Proyectos destacados",
            caseStudy: {
                badge: "Caso de estudio · Código confidencial",
                title: "Plataforma de gestión de riesgo y cumplimiento",
                context: "Risk Consulting · 2026 · KYC / SAGRILAFT / PTEE",
                problemTitle: "El reto",
                problem: "Empresas de sectores regulados deben conocer y evaluar a sus contrapartes (clientes, proveedores, aliados). El sistema anterior en PHP era difícil de mantener: cada formulario nuevo implicaba desarrollo y los flujos de aprobación estaban acoplados al código.",
                solutionTitle: "La solución",
                solution: "Una plataforma nueva, construida de punta a punta, donde formularios, reglas y flujos se configuran con datos, integrada con firma electrónica, SSO corporativo y validación contra listas restrictivas.",
                architectureTitle: "Arquitectura",
                architecture: [
                    { name: "Angular 21", detail: "SSR · Zoneless · Signals" },
                    { name: "ASP.NET Core 9", detail: "API REST · Clean Architecture" },
                    { name: "SQL Server", detail: "75+ migraciones versionadas" },
                ],
                integrations: ["Adobe Sign", "Microsoft Entra ID", "Inspektor", "Cloudflare Turnstile", "SMTP"],
                decisionsTitle: "Decisiones técnicas",
                decisions: [
                    { title: "Formularios guiados por metadata", text: "12 tipos de campo, cascadas de catálogos, filas repetibles y un motor de reglas de visibilidad condicional." },
                    { title: "Máquina de estados multi-rol", text: "Aprobaciones entre 6 roles con devoluciones, escalamiento a validadores, tareas y notificaciones." },
                    { title: "Seguridad por diseño", text: "JWT con refresh token, control de acceso por rol y recurso, rate limiting, BCrypt y auditoría." },
                    { title: "Migración sin pérdida", text: "Mapeo de estados y catálogos, deduplicación de personas y firmas históricas desde el sistema V1." },
                ],
                metrics: [
                    { value: "0", label: "líneas de código para crear un formulario nuevo" },
                    { value: "12", label: "tipos de campo dinámicos" },
                    { value: "6", label: "roles en flujos de aprobación" },
                    { value: "75+", label: "migraciones de base de datos" },
                ],
            },
            others: {
                title: "Otros proyectos",
                description: "NyGSoft · 2024 - 2026 · Sistemas empresariales en los que trabajé como desarrollador full stack",
                items: [
                    {
                        title: "Portal de acceso a aplicaciones",
                        featured: true,
                        description: "Microservicio y portal web que centraliza el acceso a las aplicaciones de la organización. Administra aplicaciones, perfiles, módulos y permisos por acción, con autenticación JWT, contraseñas con BCrypt y consulta de grupos de Microsoft Graph. Clean Architecture en capas API, Core e Infrastructure.",
                        stack: [".NET 8", "EF Core", "SQL Server", "React", "PrimeReact", "JWT"],
                    },
                    {
                        title: "Microservicio de gestión de usuarios",
                        featured: true,
                        description: "API REST para registrar personas naturales y empresas, activar cuentas, generar, cambiar y recuperar contraseñas, emitir tokens y sincronizar usuarios con Microsoft Graph. Incluye health checks, métricas con Prometheus, logs estructurados con Serilog y pruebas con xUnit y Moq.",
                        stack: [".NET 8", "EF Core", "SQL Server", "xUnit", "Prometheus", "React"],
                    },
                    {
                        title: "Conciliación de procesos BPM",
                        featured: true,
                        description: "Microservicio que desacopla el sistema BPM de las aplicaciones que lo consumen: expone los procesos por conciliar, sus partes y actuaciones a partir de servicios SOAP, con autenticación OAuth, cifrado y trazabilidad con Serilog.",
                        stack: [".NET 8", "SOAP / WCF", "JWT", "Serilog", "xUnit"],
                    },
                    {
                        title: "Liquidación y pago de sentencias judiciales",
                        featured: true,
                        description: "Plataforma que liquida y gestiona el pago a beneficiarios de sentencias. Desarrollé la solicitud y el cargue del certificado de disponibilidad presupuestal (CDP), la notificación y el cargue de oficios de pago, la gestión de firma electrónica y el rediseño responsive.",
                        stack: ["Laravel", "Vue 3", "PrimeVue", "Oracle"],
                    },
                    {
                        title: "Gestión documental y radicación",
                        description: "Sistema multiempresa (multi-tenant) de radicación de correspondencia y expedientes. Construí la relación entre radicados y expedientes, las reglas de negocio de radicación, el envío de correos, el login centralizado con código de verificación y la migración de usuarios.",
                        stack: ["Laravel", "Vue", "Inertia", "MySQL"],
                    },
                    {
                        title: "Instalaciones en campo: web y app móvil",
                        description: "Gestión de instalación de dispositivos por técnicos en campo. Hice los módulos de usuarios, zonas y asignación de técnicos, las migraciones de base de datos, la pasarela de pagos con QR y bitácora de pagos, las notificaciones y el contador de instalaciones en la app.",
                        stack: ["CodeIgniter 4", "MySQL", "Ionic", "Vue 3", "Capacitor"],
                    },
                    {
                        title: "Monitoreo de tráfico y rutas de transporte",
                        description: "Seguimiento de vehículos de carga por rutas y puestos de control. Implementé el registro de geolocalizaciones, el cálculo de distancias por latitud y longitud, la integración con un proveedor de rastreo GPS, alertas, cargues masivos y un nuevo login con captcha.",
                        stack: ["CodeIgniter 4", "MySQL", "jQuery", "Geolocalización"],
                    },
                    {
                        title: "CRM de casos y clientes",
                        description: "Gestión de casos, clientes, tickets y calendario para una firma de servicios migratorios. Desarrollé el chat en tiempo real con WebSockets y notificaciones, la réplica de citas, ingresos y egresos, pagos por cuotas, el módulo de vehículos y reportes en Excel y PDF.",
                        stack: ["CodeIgniter 4", "WebSockets", "MySQL", "jQuery"],
                    },
                    {
                        title: "Evaluación de proveedores",
                        description: "Evaluaciones periódicas de proveedores con cuestionarios por categoría. Construí la asignación y la evaluación masiva, el cargue masivo de proveedores y usuarios, las notificaciones por correo y los reportes.",
                        stack: ["CodeIgniter 4", "MySQL", "jQuery"],
                    },
                    {
                        title: "Administración de propiedad horizontal",
                        description: "Gestión de copropietarios, residentes, parqueaderos, mascotas, empleados y equipos. Desarrollé el calendario de mantenimiento con tareas programadas, los cargues masivos, mejoras al constructor de formularios y exportes a PDF y Excel en todos los módulos.",
                        stack: ["CodeIgniter 4", "MySQL", "jQuery"],
                    },
                    {
                        title: "Remisiones, báscula y pedidos",
                        description: "Control de despachos con pesaje en báscula y consecutivos de remisiones integrados con NetSuite, y un sistema de pedidos. Trabajé en remisiones, consecutivos, filtros, exportes y reportes de pedidos.",
                        stack: ["CodeIgniter 4", "NetSuite", "MySQL"],
                    },
                    {
                        title: "Contabilidad y facturación",
                        description: "Facturas de compra y venta, impuestos, retenciones, gastos y nómina. Desarrollé los módulos de impuestos y empleados, los filtros de la bitácora de accesos y el listado de ventas.",
                        stack: ["CodeIgniter 4", "MySQL", "jQuery"],
                    },
                ],
            },
        },
        skills: {
            title: "Habilidades técnicas",
            legend: "Uso diario en producción",
            categories: [
                {
                    title: "Backend",
                    icon: "./assets/images/backend.png",
                    items: [
                        { name: "C# / ASP.NET Core", core: true },
                        { name: "Arquitectura en capas", core: true },
                        { name: "ADO.NET / EF Core" },
                        { name: "ASP.NET MVC 5" },
                        { name: "PHP (Laravel, CodeIgniter)" },
                        { name: "Java (Spring Boot)" },
                    ],
                },
                {
                    title: "Frontend",
                    icon: "./assets/images/interfaz.png",
                    items: [
                        { name: "Angular 21 (Signals, Zoneless, SSR)", core: true },
                        { name: "TypeScript", core: true },
                        { name: "React (PrimeReact)" },
                        { name: "Vue.js (PrimeVue)" },
                        { name: "jQuery" },
                        { name: "HTML5 / CSS3 responsive" },
                    ],
                },
                {
                    title: "Bases de datos",
                    icon: "./assets/images/herramientas.png",
                    items: [
                        { name: "SQL Server", core: true },
                        { name: "Migraciones versionadas", core: true },
                        { name: "MySQL" },
                        { name: "Oracle" },
                        { name: "Consultas analíticas e indexación" },
                    ],
                },
                {
                    title: "Seguridad e integraciones",
                    icon: "./assets/images/backend.png",
                    items: [
                        { name: "JWT y Refresh Tokens", core: true },
                        { name: "SSO Entra ID (OAuth 2.0 / OIDC)", core: true },
                        { name: "Control de acceso por rol", core: true },
                        { name: "Adobe Sign", core: true },
                        { name: "Rate limiting e IDOR" },
                        { name: "SMTP transaccional" },
                    ],
                },
                {
                    title: "Arquitectura y DevOps",
                    icon: "./assets/images/herramientas.png",
                    items: [
                        { name: "Diseño guiado por metadata", core: true },
                        { name: "SOLID / Clean Architecture", core: true },
                        { name: "Azure DevOps CI/CD", core: true },
                        { name: "Git / GitFlow", core: true },
                        { name: "Vitest" },
                        { name: "Claude Code (desarrollo con IA)" },
                    ],
                },
                {
                    title: "Habilidades blandas",
                    icon: "./assets/images/habilidades-blandas.png",
                    items: [
                        { name: "Análisis de causa raíz" },
                        { name: "Trabajo en equipo" },
                        { name: "Adaptabilidad" },
                        { name: "Comunicación con negocio" },
                    ],
                },
            ],
        },
        education: {
            title: "Estudios realizados",
            items: [
                {
                    title: "Tecnólogo en Análisis y Desarrollo de Sistemas de Información (ADSI)",
                    date: "SENA · Mar 2024",
                    responsabilities: [
                        "Desarrollo web con PHP, Java, Node.js y C# (.NET)",
                        "Administración de bases de datos MySQL",
                        "Análisis de requerimientos y diseño de soluciones",
                        "Pruebas unitarias y calidad de software",
                    ],
                },
                {
                    title: "Java y Spring Boot G6 - Oracle Next Education",
                    date: "Alura LATAM · Dic 2024",
                    responsabilities: [
                        "Spring Boot 3: Developing a REST API",
                        "Spring Boot: Data Persistence and Queries with Spring Data JPA",
                        "Spring Boot 3: Documenting, Testing, and Preparing an API for Deployment",
                    ],
                },
                {
                    title: "Bachillerato académico",
                    date: "I.E.D. Alfonso López Michelsen · Dic 2019",
                    responsabilities: [],
                },
            ],
        },
        contact: {
            title: "Contacto",
            subtitle: "¿Tienes una vacante o un proyecto? Escríbeme.",
            email: "Correo",
            linkedin: "LinkedIn",
            github: "GitHub",
            cv: "Hoja de vida",
            cvValue: "Descargar PDF",
        },
        footer: "Desarrollador Full Stack",
    },

    en: {
        nav: [
            { href: NAV_IDS.inicio, label: "Home" },
            { href: NAV_IDS.experiencia, label: "Experience" },
            { href: NAV_IDS.proyectos, label: "Projects" },
            { href: NAV_IDS.habilidades, label: "Skills" },
            { href: NAV_IDS.estudios, label: "Education" },
        ],
        ui: {
            contactBtn: "Contact me",
            langToggle: "ES",
            langToggleLabel: "Ver en español",
            menuLabel: "Open menu",
            downloadCv: "Download CV",
            current: "Current",
            highlights: "Key achievements",
            showAllTasks: "See all responsibilities",
            featured: "Featured",
        },
        hero: {
            role: "Full Stack Developer",
            summary: "Systems Analysis and Development technologist focused on backend and application architecture. I currently build risk management and compliance platforms with Angular 21 and ASP.NET Core 9: systems integration, security, data processing and process automation.",
            facts: [
                { icon: "location_on", text: "Bogotá, Colombia" },
                { icon: "work_history", text: "Building software since 2023" },
                { icon: "translate", text: "English B1" },
            ],
            photoAlt: "Photo of Juan David Ducuara",
        },
        experience: {
            title: "Work experience",
            items: [
                {
                    role: "Software Development Engineer",
                    company: "Risk Consulting",
                    location: "Bogotá, Colombia",
                    date: "Mar 2026 - Present",
                    current: true,
                    highlights: [
                        "Built the frontend and backend of a new platform with Angular 21 and ASP.NET Core 9, replacing a legacy PHP system",
                        "Designed metadata-driven dynamic forms: a new form is created with data only, without touching code",
                        "Closed an IDOR vulnerability by implementing role- and resource-based access control",
                        "Set up CI/CD in Azure DevOps with CalVer versioning and promotion across Test, Staging and Production",
                    ],
                    responsabilities: [
                        "Development of risk management and compliance web platforms (KYC / SAGRILAFT / PTEE) for pharmaceutical, energy, consumer goods and industrial clients",
                        "Multi-role approval workflows (Counterparty, BPO, Compliance, Legal, Business Owner, Administrator) with a state machine, returns, escalation, tasks and notifications",
                        "Integrations with Adobe Sign (multiple signers and webhooks), Microsoft Entra ID / SSO, Inspektor (sanctions list screening), Cloudflare Turnstile and SMTP with editable templates",
                        "Risk scoring and profiling modules and control matrices with residual risk calculation",
                        "Reporting and KPIs: audit logs, role-based dashboards and Excel/PDF exports with server-side pagination",
                        "Data migration from the PHP/V1 system to V2: status and catalog mapping, person deduplication, historical signatures and bulk Excel uploads",
                        "Security with JWT and refresh tokens, rate limiting, BCrypt hashing and action auditing",
                        "75+ versioned database migrations, atomic transactions, SOLID, Clean Architecture and conventional commits",
                        "Maintenance and bug fixing of legacy apps in ASP.NET MVC 5 / EF6, Laravel and plain PHP, deployed on IIS",
                        "Responsive, bilingual (ES/EN) interfaces with dark mode, accessibility and guided tutorials",
                    ],
                    stack: ["Angular 21", "ASP.NET Core 9", "SQL Server", "Azure DevOps", "Entra ID", "Adobe Sign"],
                },
                {
                    role: "Full Stack Developer",
                    company: "NyGSoft SAS",
                    location: "Bogotá, Colombia",
                    date: "Apr 2024 - Feb 2026",
                    highlights: [
                        "Developed enterprise applications in C# / .NET following SOLID and Clean Architecture",
                        "Implemented microservices and RESTful APIs with middleware, versioning and JWT security",
                        "Built SPA interfaces with React (PrimeReact) and Vue (PrimeVue) integrated with REST APIs",
                    ],
                    responsabilities: [
                        "Integration of external APIs and internal services using Repository and Unit of Work patterns",
                        "SQL Server, Oracle and MySQL databases: optimized queries, stored procedures and Entity Framework Core",
                        "Maintenance of PHP systems (Laravel, CodeIgniter 4) and RESTful APIs in Laravel with MVC architecture",
                        "jQuery interfaces for internal modules",
                        "Functional analysis, technical design, documentation and task estimation in cross-functional teams",
                    ],
                    stack: [".NET", "C#", "React", "Vue", "Laravel", "SQL Server", "Oracle"],
                },
                {
                    role: "Information Systems Development Intern",
                    company: "AOA Colombia",
                    location: "Bogotá, Colombia",
                    date: "Aug 2023 - Feb 2024",
                    highlights: [
                        "Developed and maintained web modules with PHP, JavaScript and MySQL",
                        "Built and consumed REST APIs to integrate systems",
                    ],
                    responsabilities: [
                        "Relational database design",
                        "Backend business logic and validations",
                        "Functional testing and bug fixing",
                    ],
                    stack: ["PHP", "JavaScript", "MySQL"],
                },
            ],
        },
        projects: {
            title: "Featured projects",
            caseStudy: {
                badge: "Case study · Confidential code",
                title: "Risk management and compliance platform",
                context: "Risk Consulting · 2026 · KYC / SAGRILAFT / PTEE",
                problemTitle: "The challenge",
                problem: "Companies in regulated industries must know and assess their counterparties (clients, suppliers, partners). The previous PHP system was hard to maintain: every new form required development work and approval workflows were coupled to the code.",
                solutionTitle: "The solution",
                solution: "A new platform, built end to end, where forms, rules and workflows are configured with data, integrated with e-signature, corporate SSO and sanctions list screening.",
                architectureTitle: "Architecture",
                architecture: [
                    { name: "Angular 21", detail: "SSR · Zoneless · Signals" },
                    { name: "ASP.NET Core 9", detail: "REST API · Clean Architecture" },
                    { name: "SQL Server", detail: "75+ versioned migrations" },
                ],
                integrations: ["Adobe Sign", "Microsoft Entra ID", "Inspektor", "Cloudflare Turnstile", "SMTP"],
                decisionsTitle: "Technical decisions",
                decisions: [
                    { title: "Metadata-driven forms", text: "12 field types, cascading catalogs, repeatable rows and a conditional visibility rules engine." },
                    { title: "Multi-role state machine", text: "Approvals across 6 roles with returns, escalation to validators, tasks and notifications." },
                    { title: "Security by design", text: "JWT with refresh tokens, role- and resource-based access control, rate limiting, BCrypt and auditing." },
                    { title: "Lossless migration", text: "Status and catalog mapping, person deduplication and historical signatures from the V1 system." },
                ],
                metrics: [
                    { value: "0", label: "lines of code to create a new form" },
                    { value: "12", label: "dynamic field types" },
                    { value: "6", label: "roles in approval workflows" },
                    { value: "75+", label: "database migrations" },
                ],
            },
            others: {
                title: "Other projects",
                description: "NyGSoft · 2024 - 2026 · Business systems I worked on as a full stack developer",
                items: [
                    {
                        title: "Application access portal",
                        featured: true,
                        description: "Microservice and web portal that centralizes access to the organization's applications. It manages applications, profiles, modules and per-action permissions, with JWT authentication, BCrypt-hashed passwords and Microsoft Graph group lookups. Clean Architecture with API, Core and Infrastructure layers.",
                        stack: [".NET 8", "EF Core", "SQL Server", "React", "PrimeReact", "JWT"],
                    },
                    {
                        title: "User management microservice",
                        featured: true,
                        description: "REST API to register individuals and companies, activate accounts, generate, change and recover passwords, issue tokens and sync users with Microsoft Graph. Includes health checks, Prometheus metrics, structured logging with Serilog and tests with xUnit and Moq.",
                        stack: [".NET 8", "EF Core", "SQL Server", "xUnit", "Prometheus", "React"],
                    },
                    {
                        title: "BPM process reconciliation",
                        featured: true,
                        description: "Microservice that decouples the BPM system from the applications that consume it: it exposes processes pending reconciliation, their parties and proceedings from SOAP services, with OAuth authentication, encryption and Serilog tracing.",
                        stack: [".NET 8", "SOAP / WCF", "JWT", "Serilog", "xUnit"],
                    },
                    {
                        title: "Court ruling settlement and payments",
                        featured: true,
                        description: "Platform that calculates and manages payments to beneficiaries of court rulings. I built the budget availability certificate (CDP) request and upload flow, payment letter notifications and uploads, e-signature management and the responsive redesign.",
                        stack: ["Laravel", "Vue 3", "PrimeVue", "Oracle"],
                    },
                    {
                        title: "Document management and filing",
                        description: "Multi-tenant system for filing correspondence and case files. I built the link between filings and case files, the filing business rules, email delivery, centralized login with a verification code and the user migration.",
                        stack: ["Laravel", "Vue", "Inertia", "MySQL"],
                    },
                    {
                        title: "Field installations: web and mobile app",
                        description: "Management of device installations by field technicians. I built the users, zones and technician assignment modules, database migrations, the payment gateway with QR codes and payment logs, notifications and the installation counter in the app.",
                        stack: ["CodeIgniter 4", "MySQL", "Ionic", "Vue 3", "Capacitor"],
                    },
                    {
                        title: "Traffic and transport route monitoring",
                        description: "Tracking of cargo vehicles across routes and checkpoints. I implemented geolocation logging, distance calculation from latitude and longitude, integration with a GPS tracking provider, alerts, bulk uploads and a new login with captcha.",
                        stack: ["CodeIgniter 4", "MySQL", "jQuery", "Geolocation"],
                    },
                    {
                        title: "Case and client CRM",
                        description: "Case, client, ticket and calendar management for an immigration services firm. I built real-time chat with WebSockets and notifications, appointment replication, income and expenses, installment payments, the vehicles module and Excel/PDF reports.",
                        stack: ["CodeIgniter 4", "WebSockets", "MySQL", "jQuery"],
                    },
                    {
                        title: "Supplier evaluation",
                        description: "Periodic supplier evaluations with questionnaires by category. I built bulk assignment and evaluation, bulk upload of suppliers and users, email notifications and reports.",
                        stack: ["CodeIgniter 4", "MySQL", "jQuery"],
                    },
                    {
                        title: "Residential property management",
                        description: "Management of owners, residents, parking spots, pets, staff and equipment. I built the maintenance calendar with scheduled tasks, bulk uploads, form builder improvements and PDF/Excel exports across all modules.",
                        stack: ["CodeIgniter 4", "MySQL", "jQuery"],
                    },
                    {
                        title: "Delivery notes, weighing and orders",
                        description: "Dispatch control with truck scale weighing and delivery note numbering integrated with NetSuite, plus an order system. I worked on delivery notes, numbering, filters, exports and order reports.",
                        stack: ["CodeIgniter 4", "NetSuite", "MySQL"],
                    },
                    {
                        title: "Accounting and invoicing",
                        description: "Purchase and sales invoices, taxes, withholdings, expenses and payroll. I built the taxes and employees modules, access log filters and the sales list.",
                        stack: ["CodeIgniter 4", "MySQL", "jQuery"],
                    },
                ],
            },
        },
        skills: {
            title: "Technical skills",
            legend: "Daily use in production",
            categories: [
                {
                    title: "Backend",
                    icon: "./assets/images/backend.png",
                    items: [
                        { name: "C# / ASP.NET Core", core: true },
                        { name: "Layered architecture", core: true },
                        { name: "ADO.NET / EF Core" },
                        { name: "ASP.NET MVC 5" },
                        { name: "PHP (Laravel, CodeIgniter)" },
                        { name: "Java (Spring Boot)" },
                    ],
                },
                {
                    title: "Frontend",
                    icon: "./assets/images/interfaz.png",
                    items: [
                        { name: "Angular 21 (Signals, Zoneless, SSR)", core: true },
                        { name: "TypeScript", core: true },
                        { name: "React (PrimeReact)" },
                        { name: "Vue.js (PrimeVue)" },
                        { name: "jQuery" },
                        { name: "Responsive HTML5 / CSS3" },
                    ],
                },
                {
                    title: "Databases",
                    icon: "./assets/images/herramientas.png",
                    items: [
                        { name: "SQL Server", core: true },
                        { name: "Versioned migrations", core: true },
                        { name: "MySQL" },
                        { name: "Oracle" },
                        { name: "Analytical queries and indexing" },
                    ],
                },
                {
                    title: "Security & integrations",
                    icon: "./assets/images/backend.png",
                    items: [
                        { name: "JWT & Refresh Tokens", core: true },
                        { name: "Entra ID SSO (OAuth 2.0 / OIDC)", core: true },
                        { name: "Role-based access control", core: true },
                        { name: "Adobe Sign", core: true },
                        { name: "Rate limiting & IDOR" },
                        { name: "Transactional SMTP" },
                    ],
                },
                {
                    title: "Architecture & DevOps",
                    icon: "./assets/images/herramientas.png",
                    items: [
                        { name: "Metadata-driven design", core: true },
                        { name: "SOLID / Clean Architecture", core: true },
                        { name: "Azure DevOps CI/CD", core: true },
                        { name: "Git / GitFlow", core: true },
                        { name: "Vitest" },
                        { name: "Claude Code (AI-assisted dev)" },
                    ],
                },
                {
                    title: "Soft skills",
                    icon: "./assets/images/habilidades-blandas.png",
                    items: [
                        { name: "Root cause analysis" },
                        { name: "Teamwork" },
                        { name: "Adaptability" },
                        { name: "Business communication" },
                    ],
                },
            ],
        },
        education: {
            title: "Education",
            items: [
                {
                    title: "Technologist in Information Systems Analysis and Development (ADSI)",
                    date: "SENA · Mar 2024",
                    responsabilities: [
                        "Web development with PHP, Java, Node.js and C# (.NET)",
                        "MySQL database administration",
                        "Requirements analysis and solution design",
                        "Unit testing and software quality",
                    ],
                },
                {
                    title: "Java and Spring Boot G6 - Oracle Next Education",
                    date: "Alura LATAM · Dec 2024",
                    responsabilities: [
                        "Spring Boot 3: Developing a REST API",
                        "Spring Boot: Data Persistence and Queries with Spring Data JPA",
                        "Spring Boot 3: Documenting, Testing, and Preparing an API for Deployment",
                    ],
                },
                {
                    title: "High school diploma",
                    date: "I.E.D. Alfonso López Michelsen · Dec 2019",
                    responsabilities: [],
                },
            ],
        },
        contact: {
            title: "Contact",
            subtitle: "Have an opening or a project? Get in touch.",
            email: "Email",
            linkedin: "LinkedIn",
            github: "GitHub",
            cv: "Resume",
            cvValue: "Download PDF",
        },
        footer: "Full Stack Developer",
    },
}
